### ISSUE TITLE
How to install the driver without helm?

### ISSUE THREAD

**Issue by SuperJMN** [seaweedfs/seaweedfs-csi-driver#137]
I prefer not to use helm. 
Is there a workflow to do this kind of installation?

Thanks.

**Comment by achetronic** [comment]
@SuperJMN Another possibility is using kustomize (it's integrated on kubectl) to generate the manifests as @Jackbennett suggested but using a kustomization.yaml, instead of helm directly:

https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md

basically generate a kustomization.yaml file with that spec as seen in the sample and then `kubectl kustomize . | kubectl apply -f -`

**Comment by bmm-alc** [comment]
this issue could be closed no ?
